### PR TITLE
Threat Intel Analytics

### LINKED ISSUE #1117: [META] Threat Intelligence Analytics In OpenSearch

### PR DESCRIPTION
**Pull request by eirsep**
### Description
[Describe what this change achieves]
 
### Issues Resolved
#1117 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by AWSHurneyt** [comment]
Regarding the following jar hell issue in the CI:
https://github.com/opensearch-project/security-analytics/actions/runs/9720020887/job/26830800682?pr=1098#step:6:125
```
#8 2.113 jar1: /usr/share/opensearch/plugins/opensearch-job-scheduler/guava-32.1.3-jre.jar
#8 2.113 jar2: /usr/share/opensearch/plugins/opensearch-alerting/guava-32.0.1-jre.jar
```
The google guava dependency was removed in PR https://github.com/opensearch-project/alerting/pull/1571

Tried a few means to exclude google guave in this dummy PR, but that did not resolve the issue.
1. https://github.com/AWSHurneyt/security-analytics/pull/3/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R152
2. https://github.com/AWSHurneyt/security-analytics/pull/3/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R178

Unsure why the alerting artifact would still include that dependency; reached out to @sbcd90 for insight.

**Comment by sbcd90** [comment]
> Regarding the following jar hell issue in the CI: https://github.com/opensearch-project/security-analytics/actions/runs/9720020887/job/26830800682?pr=1098#step:6:125
> 
> ```
> #8 2.113 jar1: /usr/share/opensearch/plugins/opensearch-job-scheduler/guava-32.1.3-jre.jar
> #8 2.113 jar2: /usr/share/opensearch/plugins/opensearch-alerting/guava-32.0.1-jre.jar
> ```
> 
> The google guava dependency was removed in PR [opensearch-project/alerting#1571](https://github.com/opensearch-project/alerting/pull/1571)
> 
> Tried a few means to exclude google guave in this dummy PR, but that did not resolve the issue.
> 
> 1. https://github.com/AWSHurneyt/security-analytics/pull/3/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R152
> 2. https://github.com/AWSHurneyt/security-analytics/pull/3/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R178
> 
> Unsure why the alerting artifact would still include that dependency; reached out to @sbcd90 for insight.

hi @AWSHurneyt , the test failures https://github.com/opensearch-project/security-analytics/actions/runs/9720020887/job/26830800682?pr=1098#step:6:125 are due to the latest docker image not being updated with alerting remote monitor changes.
But i see some of the threat intel tests failing. https://github.com/opensearch-project/security-analytics/actions/runs/9727738710/job/26847616424?pr=1098
Please have a look at them.

**Comment by AWSHurneyt** [comment]
The `EnabledIfSystemProperty` annotation ([example](https://github.com/opensearch-project/security-analytics/blob/feature/threat_intel/src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java#L64)) in the `TestS3ConnectionRestIT`, and `SATIFSourceConfigRestApiIT` test suites should prevent them from running in the CIs.
#### Those test failures can be ignored.
As mentioned in the test doc comment ([example](https://github.com/opensearch-project/security-analytics/blob/feature/threat_intel/src/test/java/org/opensearch/securityanalytics/resthandler/TestS3ConnectionRestIT.java#L30)), they require certain parameters to be provided in order to run successfully. Those parameters are not currently configured to be provided by the github CI, so the tests **will** fail.

Will investigate why the `EnabledIfSystemProperty` annotation is allowing those tests to run, and raise a separate PR to fix that.

**Review by AWSHurneyt — APPROVED** [review]
https://github.com/opensearch-project/security-analytics/pull/1098#issuecomment-2198859569 calls out that the security tests are failing because the docker image used by those tests hasn't been updated.

**Review by amsiglan — APPROVED** [review]

**Pull request merged**
