### PR TITLE
Reduce log level for informative message

### PR DESCRIPTION
**Pull request by eht16**
### Description
In org.opensearch.securityanalytics.indexmanagment/DetectorIndexManagementService there is a log message "info deleteOldIndices" which is more of a trace but it is logged with level error.

In my logs see the following entries (repeated every 12 hours):
```
Dec 17 11:26:39 hostname opensearch[104377]: [INFO ][o.o.a.t.CronTransportAction] [n1-kalgo] Start running AD hourly cron.
Dec 17 11:26:39 hostname opensearch[104377]: [INFO ][o.o.a.t.ADTaskManager    ] [n1-kalgo] Start to maintain running historical tasks
Dec 17 11:26:39 hostname opensearch[104377]: [INFO ][o.o.a.c.HourlyCron       ] [n1-kalgo] Hourly maintenance succeeds
Dec 17 11:26:39 hostname opensearch[104377]: [ERROR][o.o.s.i.DetectorIndexManagementService] [n1-kalgo] info deleteOldIndices
Dec 17 11:26:39 hostname opensearch[104377]: [INFO ][o.o.s.i.DetectorIndexManagementService] [n1-kalgo] No Old Finding Indices to delete
Dec 17 11:26:39 hostname opensearch[104377]: [ERROR][o.o.s.i.DetectorIndexManagementService] [n1-kalgo] info deleteOldIndices
Dec 17 11:26:39 hostname opensearch[104377]: [INFO ][o.o.s.i.DetectorIndexManagementService] [n1-kalgo] No Old Alert Indices to delete
Dec 17 11:26:39 hostname opensearch[104377]: [INFO ][o.o.i.i.IndexStateManagementHistory] [n1-kalgo] No Old History Indices to delete
```
This is fine except the "info deleteOldIndices" which is logged as error but seems like an info or debug message, unless I'm missing anything.

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by getsaurabh02 — COMMENTED** [review]
Thanks @eht16 for taking a stab on it. LGTM.

**Comment by getsaurabh02** [comment]
@eht16 Can we fix the DCO check in the commit

**Comment by eht16** [comment]
> @eht16 Can we fix the DCO check in the commit

@getsaurabh02 done (hopefully correctly).

**Comment by eht16** [comment]
Anything else missing?

**Comment by nkonev** [comment]
@getsaurabh02 also bumped into this issue by my monitoring

can you merge this PR ?

**Comment by sbcd90** [comment]
triggering build

**Review by getsaurabh02 — APPROVED** [review]

**Review by sbcd90 — APPROVED** [review]

**Comment by terryquigleysas** [comment]
Hi, could someone confirm whether this change was backported for 2.9.0 or not? If it hasn't been are there plans for it to be in the 2.10.0 release?

**Comment by terryquigleysas** [comment]
@eht16  Hi, would you be able to confirm whether this change was backported for 2.9.0 or not? If it hasn't been are there plans for it to be in the 2.10.0 release?

Thanks

**Comment by eht16** [comment]
@terryquigleysas I cannot say for sure if the change is in 2.9.0, I do not see the originally reported log messages anymore.
But now there are messages like:
```
opensearch[550]: [2023-09-13T12:45:12,860][ERROR][o.o.a.a.AlertIndices     ] [n1-kalgo] info deleteOldIndices
```
Maybe the log message was moved or so in the meantime.

**Pull request merged**
