### PR TITLE
Benchmark

### PR DESCRIPTION
**Pull request by phaseshiftg**
This PR adds a gatling benchmark submodule with several tests and gradle integration. 
It also adds a github workflow for triggering the benchmark
There are some example command lines in benchmark/README.md

### CODE REVIEW

**Review by eirsep — COMMENTED** [review]
i dont see any github workflow added i.e. no yml file under .github folder found as claimed in description
@phaseshiftg  
Am i missing something?

**Comment by eirsep** [comment]
is `benchmark/README.md` supposed to be pushed as a part of this PR itself?

**Comment by getsaurabh02** [comment]
@phaseshiftg Are you still active on this? And would you like to contribute this to the project workflow?

**Comment by dblock** [comment]
Closing as stalled, feel free to finish and reopen @phaseshiftg.

[Catch All Triage, attendees [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/lukas-vlcek/), [4](https://github.com/rafaelma), [5](https://github.com/krisfreedain), [6](https://github.com/gargrajat), [7](https://github.com/andrross)]

**Pull request closed without merging**
