### PR TITLE
Delete detector successfully if workflow is missing (#790)

### PR DESCRIPTION
**Pull request by engechas**
* Delete detector successfully if workflow is missing

Signed-off-by: Chase Engelbrecht <engechas@amazon.com>

* Refactor to use existing NotFound exception checker

Signed-off-by: Chase Engelbrecht <engechas@amazon.com>

---------

Signed-off-by: Chase Engelbrecht <engechas@amazon.com>
(cherry picked from commit 0ad91ccecd846439bb3136390e2defbf59eb9e10)

### Description
Manual conflict resolution + backport
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [N/A] New functionality has been documented.
  - [N/A] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jowg-amazon** [comment]
Can you rebase from 2.x? Checks are failing because of the gradle update.

**Comment by engechas** [comment]
> > Can you rebase from 2.x? Checks are failing because of the gradle update.
> 
> Done

Nvm, still failing. It doesn't look related to this PR but will investigate soon

**Comment by engechas** [comment]
This is the failure:
```
org.opensearch.securityanalytics.findings.FindingIT > testGetFindings_rolloverByMaxAge_success FAILED
    java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at __randomizedtesting.SeedInfo.seed([C511499764CAA34E:81FC4FA1CAEA296F]:0)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:374)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at org.opensearch.securityanalytics.findings.FindingIT.testGetFindings_rolloverByMaxAge_success(FindingIT.java:325)
```

I confirmed it still occurs with my backported commit removed.

**Comment by jowg-amazon** [comment]
Yeah this is a known flakey test in SA. I'm taking a look into it now.

**Review by praveensameneni — APPROVED** [review]

**Review by jowg-amazon — APPROVED** [review]

**Pull request merged**
