### PR TITLE
Update to Gradle 8.5

### PR DESCRIPTION
**Pull request by reta**
### Description
Update to Gradle 8.5
 
### Issues Resolved
Part of https://github.com/opensearch-project/OpenSearch/issues/10334
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by jowg-amazon — APPROVED** [review]

**Comment by eirsep** [comment]
why have our test workflows not run on this?
that would give us confidence to merge

**Comment by reta** [comment]
> why have our test workflows not run on this?

No idea (question to maintainers) but thanks for looking @eirsep

**Comment by jowg-amazon** [comment]
Approved the workflow run.

**Comment by jowg-amazon** [comment]
Failing CI's are due to Lucene upgrade which should be fixed in this PR #800

**Comment by jowg-amazon** [comment]
Closing PR in favor of #800 which cherry-picks this PR for gradle upgrade to 8.5 because CI's were failing without both PRs.

**Pull request closed without merging**
