### PR TITLE
[Refactor] rebase to support latest core snapshot

### PR DESCRIPTION
**Pull request by nknize**
This PR refactors the codebase to comply with latest breaking changes on the core repository. It also updates gradle to the same version as core (currently 8.2.1) and adds initial support for spotless plugin.

### CODE REVIEW

**Comment by peternied** [comment]
@nknize Hmm, are you expecting to have the formatter run when running `gradlew assemble`?

In the security repo we don't have any task dependency to it in our security plugin, instead we have separate [code hygiene workflows](https://github.com/opensearch-project/security/blob/f299a5f9094597648fbb147e74166d48090df6c9/.github/workflows/code-hygiene.yml#L16-L29) that trigger the task. 

Confirmed this was the case for the security plugin by using [gradle-task-tree](https://github.com/dorongold/gradle-task-tree)
```
./gradlew spotlessCheck taskTree 
...
:spotlessCheck
+--- :spotlessJavaCheck
|    \--- :spotlessJava
|         \--- :spotlessInternalRegisterDependencies
\--- :spotlessMiscCheck
     \--- :spotlessMisc
          \--- :spotlessInternalRegisterDependencies *
```

**Review by getsaurabh02 — APPROVED** [review]
security tests are failing since docker image are not up to date.

**Comment by sbcd90** [comment]
hi @peternied , will look into it.

**Pull request merged**
